using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace P3PPC.Expansion.TheAnswer.Models
{
    internal class BtlUnits
    {
        public enum BtlUnit : short
        {
            None = -1,
            PriestessMutteringTiaraRematch = 211,
            PriestessMutteringTiara2Rematch = 212,
            StatueRematch = 213,
            Statue2Rematch = 214,
            Statue3Rematch = 215,
            HangedManDeviousMayaRematch = 216,
            HangedManDeviousMaya2Rematch = 217,
            CowardlyMayaRooftop = 224,
            CowardlyMayaRooftop2 = 225,
            FortuneWheelofFortuneBuffDebuffs = 226,
            FortuneWheelofFortuneAilments = 227,
            FortuneWheelofFortuneHeal = 228,
            FortuneWheelofFortuneAtk = 229,
            FortuneWheelofFortuneAtk2 = 230,
            FortuneWheelofFortune = 231,
            FortuneWheelofFortuneCarpet = 232,
            Metis = 233,
            ShadowHero = 234,
            Akihiko = 235,
            Ken = 236,
            Junpei = 237,
            Koromaru = 238,
            Yukari = 239,
            Mitsuru = 240,
            Erebus = 241,
            ErebusDummy = 242,
            PriestessRematch = 243,
            EmpressRematch = 244,
            EmperorRematch = 245,
            HierophantRematch = 246,
            LoversRematch = 247,
            ChariotRematch = 248,
            JusticeRematch = 249,
            HermitRematch = 250,
            FortuneRematch = 251,
            StrengthRematch = 252,
            HangedManRematch = 253,
            ChariotJusticeRematchDummy = 254,
            ShadowHeroF = 255,
            Priestess = 256,
            Empress = 257,
            Emperor = 258,
            Hierophant = 259,
            Lovers = 260,
            Chariot = 261,
            Justice = 262,
            Hermit = 263,
            Chidori = 264,
            Fortune = 265,
            Strength = 266,
            Takaya = 267,
            Jin = 268,
            HangedMan = 269,
            Jin2 = 271,
            Takaya2 = 272,
            NyxAvatar = 273,
            Nyx = 274,
            PriestessMutteringTiara = 275,
            PriestessMutteringTiara2 = 276,
            ChariotJusticeDummy = 277,
            Statue = 278,
            Statue2 = 279,
            Statue3 = 280,
            HangedManDeviousMaya = 281,
            NyxAvatarFool = 282,
            NyxAvatarMagician = 283,
            NyxAvatarEmpress = 284,
            NyxAvatarEmperor = 285,
            NyxAvatarHeirophant = 286,
            NyxAvatarLovers = 287,
            NyxAvatarChariot = 288,
            NyxAvatarJustice = 289,
            NyxAvatarHermit = 290,
            NyxAvatarFortune = 291,
            NyxAvatarStrength = 292,
            NyxAvatarHangedMan = 293,
            Elizabeth = 294,
            HangedManDeviousMaya2 = 295,
            NyxAvatarDeath = 296,
            Magician = 297,
            Teo = 298,
            Margaret = 299,
        }
    }
}
